package PRC::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
  schema_class => 'PRC::Schema',
  connect_info => {
    dsn           => 'dbi:SQLite:prc.db',
    user          => '',
    password      => '',
    on_connect_do => q{PRAGMA foreign_keys = ON},
  },
);

=head1 NAME

PRC::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<PRC>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<PRC::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.65

1;
